name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1"   # Run every Monday at 08:00

jobs:
  test:
    strategy:
      # Default value (true) means that a failure in one setup, cancels other jobs.
      fail-fast: false
      matrix:
        smalltalk: [ Pharo64-11 ]
        os: [ windows-latest ]
        ston: [ .ci.ston ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup smalltalkCI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Load in New Image and Run Tests
        run: smalltalkci -s ${{ matrix.smalltalk }} ${{ matrix.ston }}
        shell: bash
        timeout-minutes: 10
--